spring:
  config:
    import: secret.yml
  flyway:
    enabled: true
    baseline-on-migrate: true
  
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect:
    show-sql: true

server:
  port: 9091
