server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:~/test;MODE=MariaDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
    show-sql: true

pureureum:
  scheme: http
  host: ec2-13-124-142-73.ap-northeast-2.compute.amazonaws.com
  port: 9091
