[[OAuth-API]]
= *OAuth API*

[[OAuth-로그인-API]]
== *1. OAuth 로그인 API*

*/oauth/login/* + (kakao, naver, google)

=== *1-1* OAuth 로그인 성공
operation::o-auth2-rest-controller-test/oAuth-login-success[snippets='http-request,request-fields,http-response,response-fields,response-cookies']

=== *1-2* OAuth 로그인 실패 - 정보 부족
- 응답으로 받은 email을 바탕으로 소셜 사용자 임시 정보 조회 및 OAuth 회원가입 진행

operation::o-auth2-rest-controller-test/oAuth-login-fail-not-enough-info[snippets='http-request,http-response']

=== *1-3* OAuth 로그인 실패 - 이미 존재하는 사용자
operation::o-auth2-rest-controller-test/oAuth-login-fail-exists-user[snippets='http-request,http-response']

[[소셜-사용자-임시-정보-조회-API]]
== *2. 소셜 사용자 임시 정보 조회 API*
- 임시 정보에 있는 없는 값을 받아서 OAuth 회원가입으로 API 요청

=== *2-1* 소셜 사용자 임시 정보 조회 성공
operation::o-auth2-rest-controller-test/temp-user-info-search-success[snippets='http-request,path-parameters,http-response,response-fields']

=== *2-2* 소셜 사용자 임시 정보 조회 실패 - 저장되어 있지 않은 이메일
operation::o-auth2-rest-controller-test/temp-user-info-search-fail-not-exists-email[snippets='http-request,http-response']

[[OAuth-회원가입-API]]
== *3. OAuth 회원가입 API*

=== *3-1* OAuth 회원가입 성공
operation::o-auth2-rest-controller-test/oAuth-register-success[snippets='http-request,request-body,request-fields,http-response,response-fields,response-cookies']

=== *3-2* OAuth 회원가입 실패 - 인증 받지 않은 전화번호
operation::o-auth2-rest-controller-test/oAuth-register-fail-invalid-phoneNumber[snippets='http-request,request-body,request-fields,http-response,response-fields']
