[[User-API]]
= *User API*

[[로그인-API]]
== *1. 로그인 API*

=== *1-1* 성공
operation::user-rest-controller-test/user-login-success[snippets='http-request,request-body,request-fields,http-response,response-fields,response-cookies']

=== *1-2* 실패 - 이메일이 유효하지 않음
operation::user-rest-controller-test/user-login-fail-not-valid-email[snippets='http-request,http-response']

=== *1-3* 실패 - 비밀번호가 일치하지 않음
operation::user-rest-controller-test/user-login-fail-not-valid-password[snippets='http-request,http-response']

[[JWT-응답-정보]]
== *2. JWT 재발급 API*

=== *2-1* 성공
operation::user-rest-controller-test/token-reissue-success[snippets='http-request,response-cookies,http-response']

[[회원가입-API]]
== *3. 회원가입 API*

=== *3-1* 성공
operation::user-rest-controller-test/user-register-success[snippets='http-request,request-body,request-fields,http-response']

=== *3-2* 실패
operation::user-rest-controller-test/user-register-fail[snippets='http-request,http-response']

[[이메일-확인-API]]
== *4. 이메일 확인 API*

=== *4-1* 성공
operation::user-rest-controller-test/user-checkEmail-success[snippets='http-request,request-body,request-fields,http-response']

=== *4-2* 실패
operation::user-rest-controller-test/user-checkEmail-fail[snippets='http-request,http-response']

[[회원-정보-조회-API]]
== *5. 회원 정보 조회 API*

=== *5-1* 성공
operation::user-rest-controller-test/get-user-info-success[snippets='http-request,http-response,response-body']

[[회원-정보-수정-API]]
== *6. 회원 정보 수정 API*

=== *6-1* 성공
operation::user-rest-controller-test/update-user-info-success[snippets='http-request,request-fields,http-response']

=== *6-2* 실패 - 닉네임이 중복된 값
operation::user-rest-controller-test/update-user-info-fail-duplicate-nickname[snippets='http-request,response-body']

=== *6-3* 실패 - 형식에 맞지 않는 정보
operation::user-rest-controller-test/update-user-info-fail[snippets='http-request,http-response']

[[프로필-이미지-수정-API]]
== *7. 프로필 이미지 수정 API*

=== *7-1* 성공
operation::user-rest-controller-test/update-profile-success[snippets='http-request,request-parts,http-response']

=== *7-2* 실패 - 원본 파일 이름이 비어있을 경우
operation::user-rest-controller-test/update-profile-original-file-name-empty-fail[snippets='http-request,http-response']

=== *7-3* 실패 - 파일 형식이 이미지가 아닐 경우
operation::user-rest-controller-test/update-profile-file-type-not-image-fail[snippets='http-request,http-response']
