name: pull-request-check

on:
  pull_request:
    branches: [ develop, main ]

env:
  SECRET_YML: ${{ secrets.SECRET_YML }}
  LOGBACK_VARIABLES: ${{ secrets.LOGBACK_VARIABLES }}
  SECRET_YML_DIR: src/main/resources
  SECRET_YML_FILE_NAME: secret.yml
  LOGBACK_VARIABLES_DIR: src/main/resources
  LOGBACK_VARIABLES_FILE_NAME: logback-variables.properties

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Copy secret.yml
        run: echo $SECRET_YML | base64 --decode > $SECRET_YML_DIR/$SECRET_YML_FILE_NAME

      - name: Copy logback-variables
        run: echo $LOGBACK_VARIABLES | base64 --decode > $LOGBACK_VARIABLES_DIR/$LOGBACK_VARIABLES_FILE_NAME

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash
